name: Firebase Continuous Deployment

on:
  push:
    branches: ['master']
jobs:
  deploy_job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        HOST: all.rit.edu
        USERNAME: all
        PORT: 22
        KEY: ${{ secrets.SSH_SECRET }}
        source: "."
        target: "/home/all/research/AccessibilityLab1/"
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: all.rit.edu
        USERNAME: all
        KEY: ${{ secrets.SSH_SECRET }}
        PORT: 22
        script: |
          pwd
          cd research/AccessibilityLab1
          npm install
          npm run-script build
