name: Continuous Deployment

on:
  push:
    branches: ['master']
jobs:
  deploy_job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        HOST: all.rit.edu
        USERNAME: all
        PORT: 22
        KEY: ${{ secrets.SSH_SECRET }}
        source: "."
        target: "/home/all/research/"
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: all.rit.edu
        USERNAME: all
        KEY: ${{ secrets.SSH_SECRET }}
        PORT: 22
        script: |
          chmod -R g+w research
          cd research/client
          npm install
          npm run-script build
          killall node
          tmux attach -t all
          cd ../server
          npm install
          node app.js
